# Generated by Django 4.0.2 on 2022-02-24 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_delete_date_post_subtitle_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='delete_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 11, 18, 27, 344820, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
