# Generated by Django 4.0.2 on 2022-02-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='delete_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
